### ISSUE TITLE
nezadaný gs://

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-ex-google-bigquery#10]
nezadal jsem cestu ke storage (v UI k tomu není nic co by mi řeklo že je to povinné a nechalo mě to nezadat) - [job](https://connection.keboola.com/admin/projects/478/jobs/118392914?q=) crashnul, na 99% díky tomu - a napsalo to

![image](https://cloud.githubusercontent.com/assets/1427901/8140276/78136238-115a-11e5-8818-a94a91863ade.png)

mělo by tam bejt něco víc konkrétního, aspoň kód chyby, když nic jinýho

**Comment by ErikZigo** [comment]
https://connection.keboola.com/admin/projects-new/478/jobs#/query/118392914/job/118392914
Predposledni event "BigQuery API request error" a v detailu je i to co google posila.

Zmenil jsem, aby se cesta ke storage musela vyplnit
