### ISSUE TITLE
Cloud Storage path after extraction

### ISSUE THREAD

**Issue by martinlepka** [keboola/kbc-ui-ex-google-bigquery#13]
Hey, 

just mentioning small improve, not bug. If you create and run extraction, it creates ugly path in to the chosen bucket. 
![screen shot 2015-06-13 at 13 03 22](https://cloud.githubusercontent.com/assets/12870728/8144267/80bc283e-11cd-11e5-861c-cefbc67652fc.png)

Would be great to have something less complicated like putting extracted csv.gz files just into chosen buckets from extraction settings.  

![screen shot 2015-06-13 at 13 09 19](https://cloud.githubusercontent.com/assets/12870728/8144268/855d61a0-11cd-11e5-8c73-af1c79fc5dc6.png)

**Comment by padak** [comment]
Čus, ono to takhle dává smysl, protože můžeš chtít 10x za sebou pustit to
samé - takže musíš oddělit joby, apod. Jinak za mě (jiné issue) je spíš
automatické mazání těhle tmp souborů.

Sent from mobile
Dne 13. 6. 2015 2:10 PM napsal uživatel "martinlepka" <
notifications@github.com>:

**Comment by martinlepka** [comment]
OK to chapu... JO to mazani by bylo super, akorat to zbytecne zvysuje cenu za BQ.  GB/TB v BQ a pak vlastne "mirror v csv" v Storage.

**Comment by padak** [comment]
Přesně tak. Je to tmp věc. Nechceš to tam nechat. Ale jinak to ven dostat
nejde...

Sent from mobile
Dne 13. 6. 2015 2:29 PM napsal uživatel "martinlepka" <
notifications@github.com>:

**Comment by ErikZigo** [comment]
Udelal jsem mazani tech dat v CloudStorage. Je ale nutne provest autorizaci, protoze to potrebuje vyssi opravneni.
