### ISSUE TITLE
Nested values shows an error + missing option to flatten the results

### ISSUE THREAD

**Issue by martinlepka** [keboola/kbc-ui-ex-google-bigquery#14]
Jedna takova vec. V BQ mám nested values (600 tabulek). Behem extrakce se zobrazí chyba: Cannot output multiple independently repeated fields at the same time. Found drive_old_value and drive_new_value

V BigQuery interface mam moznost při query nastavit Flatten results. 

"By default, BigQuery flattens all query results. To preserve nested and repeated results, select a destination table and enable Allow Large Results, then uncheck this option"

V rámci extractoru tuhle moznost nemam. Mozna je to chybějící feature, mozna jenom je potreba nejaky workaround.

**Comment by padak** [comment]
Jsony v BQ to teď nepodporuje. Pokud stačí v query říct ať to zplosti, mělo
by být jednoduché to dodělat.

Sent from mobile
Dne 14. 6. 2015 1:35 PM napsal uživatel "martinlepka" <
notifications@github.com>:

**Comment by ErikZigo** [comment]
Pridal jsem na to do UI checkbox.

![image](https://cloud.githubusercontent.com/assets/1726727/8205969/ab61f7c8-14f5-11e5-893e-7062dd5a9c16.png)


Snad to pomuze.

**Comment by padak** [comment]
Hustě! Zkusím, díky!

Sent from mobile
Dne 17. 6. 2015 1:35 PM napsal uživatel "Erik Zigo" <
notifications@github.com>:
