### ISSUE TITLE
Po založení cfg to hodí chybu

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-ex-google-bigquery#5]
která by měla být spíš warningem

![image](https://cloud.githubusercontent.com/assets/1427901/8140108/16d2c8fc-1159-11e5-990a-3bb5b196d00c.png)

**Comment by Halama** [comment]
to by chtělo asi vyřešit jinak, napsat alertem ve strance místo vyhození modalu

**Comment by ErikZigo** [comment]
Fixed in f7524b0672d30d22ebc1acc822e4ff9801ba9dfd

![image](https://cloud.githubusercontent.com/assets/1726727/8160314/dae625ce-136e-11e5-9052-027606d78688.png)
