### ISSUE TITLE
Play na konkrétní query

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-ex-google-bigquery#8]
Všechny nové extraktory umějí stáhnout jednu konkrétní položku konfigurace. BQ jen všechno najednou.

![image](https://cloud.githubusercontent.com/assets/1427901/8140208/c6c7a02a-1159-11e5-94fc-0bfb4e4928e6.png)

**Comment by ErikZigo** [comment]
Fixed in e661b7af22c2552ea46d0c5af253cbe751603b2e
