### ISSUE TITLE
Dal jsem play na novým cfg

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-ex-google-bigquery#9]
a tahá to úplně něco jinýho [job](https://connection.keboola.com/admin/projects/478/jobs/118392914?q=)

v parametrech vůbec není vidět, že jsem pustil konkrétní cfg:

![image](https://cloud.githubusercontent.com/assets/1427901/8140257/29859dd4-115a-11e5-849b-12f9dd2b554c.png)

**Comment by ErikZigo** [comment]
Fixed 2820ce605465baaa2c8cc8679c240344896c2f3e
